// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using ZocoTasks.Infrastructure.Persistence;

#nullable disable

namespace ZocoTasks.Infrastructure.Migrations
{
    [DbContext(typeof(ZocoDbContext))]
    [Migration("20260808002629_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZocoTasks.Domain.Entities.AnalisisOportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer")
                        .HasColumnName("comercio_id");

                    b.PrimitiveCollection<string>("DatosFaltantes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_faltantes");

                    b.Property<bool>("EsDegradado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_degradado");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_generacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HashContexto")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("hash_contexto");

                    b.Property<string>("ModeloUtilizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo_utilizado");

                    b.Property<short>("NivelInteres")
                        .HasColumnType("smallint")
                        .HasColumnName("nivel_interes");

                    b.PrimitiveCollection<string>("PreguntasSugeridas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preguntas_sugeridas");

                    b.Property<string>("ProximoPaso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proximo_paso");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resumen");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_analisis_oportunidad");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_analisis_oportunidad_usuario_id");

                    b.HasIndex("ComercioId", "FechaGeneracion")
                        .HasDatabaseName("ix_analisis_comercio_fecha");

                    b.HasIndex("ComercioId", "HashContexto")
                        .HasDatabaseName("ix_analisis_comercio_hash");

                    b.ToTable("analisis_oportunidad", (string)null);
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accion");

                    b.Property<string>("Cambios")
                        .HasColumnType("jsonb")
                        .HasColumnName("cambios");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_audit_log_fecha");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_audit_log_usuario_id");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_log_entidad");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Comercio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .HasColumnName("cuit");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_eliminacion");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_contacto");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer")
                        .HasColumnName("rubro_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('spanish',\n    coalesce(nombre_comercial, '') || ' ' ||\n    coalesce(nombre_contacto, '')  || ' ' ||\n    coalesce(notas, ''))", true);

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_asignado_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_comercio");

                    b.HasIndex("Cuit")
                        .IsUnique()
                        .HasDatabaseName("ux_comercio_cuit");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_comercio_estado");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("ix_comercio_fecha_creacion");

                    b.HasIndex("RubroId")
                        .HasDatabaseName("ix_comercio_rubro");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_comercio_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("UsuarioAsignadoId")
                        .HasDatabaseName("ix_comercio_usuario_asignado_id");

                    b.ToTable("comercio", (string)null);
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.EstadoComercio", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_final");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_estado_comercio");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_estado_comercio_codigo");

                    b.ToTable("estado_comercio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "Nuevo",
                            EsFinal = false,
                            Nombre = "Nuevo",
                            Orden = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "Contactado",
                            EsFinal = false,
                            Nombre = "Contactado",
                            Orden = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Codigo = "Interesado",
                            EsFinal = false,
                            Nombre = "Interesado",
                            Orden = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Codigo = "Documentacion",
                            EsFinal = false,
                            Nombre = "Documentación",
                            Orden = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Codigo = "Aprobado",
                            EsFinal = true,
                            Nombre = "Aprobado",
                            Orden = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Codigo = "Rechazado",
                            EsFinal = true,
                            Nombre = "Rechazado",
                            Orden = (short)6
                        });
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer")
                        .HasColumnName("comercio_id");

                    b.Property<short?>("EstadoAnterior")
                        .HasColumnType("smallint")
                        .HasColumnName("estado_anterior_id");

                    b.Property<short>("EstadoNuevo")
                        .HasColumnType("smallint")
                        .HasColumnName("estado_nuevo_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_historial_estado");

                    b.HasIndex("EstadoAnterior")
                        .HasDatabaseName("ix_historial_estado_estado_anterior_id");

                    b.HasIndex("EstadoNuevo")
                        .HasDatabaseName("ix_historial_estado_estado_nuevo_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historial_estado_usuario_id");

                    b.HasIndex("ComercioId", "Fecha")
                        .HasDatabaseName("ix_historial_comercio_fecha");

                    b.ToTable("historial_estado", (string)null);
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Interaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer")
                        .HasColumnName("comercio_id");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_interaccion");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("ix_interaccion_tipo_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_interaccion_usuario_id");

                    b.HasIndex("ComercioId", "Fecha")
                        .HasDatabaseName("ix_interaccion_comercio_fecha");

                    b.ToTable("interaccion", (string)null);
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rol");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_rol_nombre");

                    b.ToTable("rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rubro");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_rubro_nombre");

                    b.ToTable("rubro", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Gastronomía"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Indumentaria"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Kiosco y autoservicio"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Salud y estética"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Servicios profesionales"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Transporte y logística"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Educación"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.TipoInteraccion", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_interaccion");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_tipo_interaccion_codigo");

                    b.ToTable("tipo_interaccion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "Llamada",
                            Nombre = "Llamada"
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "WhatsApp",
                            Nombre = "WhatsApp"
                        },
                        new
                        {
                            Id = (short)3,
                            Codigo = "Reunion",
                            Nombre = "Reunión"
                        },
                        new
                        {
                            Id = (short)4,
                            Codigo = "Email",
                            Nombre = "Email"
                        },
                        new
                        {
                            Id = (short)5,
                            Codigo = "NotaInterna",
                            Nombre = "Nota interna"
                        });
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_email");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("pk_usuario_rol");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_rol_rol_id");

                    b.ToTable("usuario_rol", (string)null);
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.AnalisisOportunidad", b =>
                {
                    b.HasOne("ZocoTasks.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Analisis")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analisis_comercio");

                    b.HasOne("ZocoTasks.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_analisis_usuario");

                    b.Navigation("Comercio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ZocoTasks.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_log_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Comercio", b =>
                {
                    b.HasOne("ZocoTasks.Domain.Entities.EstadoComercio", "EstadoNavegacion")
                        .WithMany("Comercios")
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comercio_estado");

                    b.HasOne("ZocoTasks.Domain.Entities.Rubro", "Rubro")
                        .WithMany("Comercios")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comercio_rubro");

                    b.HasOne("ZocoTasks.Domain.Entities.Usuario", "UsuarioAsignado")
                        .WithMany("ComerciosAsignados")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_comercio_usuario_asignado");

                    b.Navigation("EstadoNavegacion");

                    b.Navigation("Rubro");

                    b.Navigation("UsuarioAsignado");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("ZocoTasks.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Historial")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historial_comercio");

                    b.HasOne("ZocoTasks.Domain.Entities.EstadoComercio", null)
                        .WithMany()
                        .HasForeignKey("EstadoAnterior")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_historial_estado_anterior");

                    b.HasOne("ZocoTasks.Domain.Entities.EstadoComercio", null)
                        .WithMany()
                        .HasForeignKey("EstadoNuevo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historial_estado_nuevo");

                    b.HasOne("ZocoTasks.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_historial_usuario");

                    b.Navigation("Comercio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Interaccion", b =>
                {
                    b.HasOne("ZocoTasks.Domain.Entities.Comercio", "Comercio")
                        .WithMany("Interacciones")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interaccion_comercio");

                    b.HasOne("ZocoTasks.Domain.Entities.TipoInteraccion", "TipoNavegacion")
                        .WithMany("Interacciones")
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interaccion_tipo");

                    b.HasOne("ZocoTasks.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_interaccion_usuario");

                    b.Navigation("Comercio");

                    b.Navigation("TipoNavegacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("ZocoTasks.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_rol");

                    b.HasOne("ZocoTasks.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Comercio", b =>
                {
                    b.Navigation("Analisis");

                    b.Navigation("Historial");

                    b.Navigation("Interacciones");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.EstadoComercio", b =>
                {
                    b.Navigation("Comercios");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Rubro", b =>
                {
                    b.Navigation("Comercios");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.TipoInteraccion", b =>
                {
                    b.Navigation("Interacciones");
                });

            modelBuilder.Entity("ZocoTasks.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ComerciosAsignados");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
